version: '3.8'

services:
  app:
    build: .
    ports:
      - "8001:8001"
    env_file:
      - .env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      # - GEMINI_API_KEY=${GEMINI_API_KEY} # Uncomment if Gemini is used
    restart: always
